name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macOS-latest
        raku-version:
          - 'latest'
          - '2022.07'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: macOS specific setup
        if: contains(matrix.os, 'macOS')
        run: |
          brew update
          brew install harfbuzz
          brew install fribidi
          brew install cairo
          brew reinstall fontconfig
      - name: Install Dependencies
        run: |
          zef install MacOS::NativeLib
          ensure-symlink-for harfbuzz fribidi cairo fontconfig
          zef install --/test App::Prove6
          zef --deps-only install .
      - name: Run Tests
        run: |
          prove6 -I. t
          zef install .
